export const Exp = [
  {
    id: 1,
    project: "JolMer",
    img: "/Icons/jolmer2.png",
    project_description: "Competition and volunteer event system",
    project_date: "May 19, 2023 - Present",
    job_level: "Entry Level",
    Type: "Bootcamp",
    Company: "Bootcamp form KDC (KIT)",
    position: "Frontend Developer",
    project_id: "Event hosting",
    work_exp: [
      "- Led the frontend development team in the successful delivery of the bootcamp platform for Competition and volunteer opportunities.",
      "- Collaborated with a team of developers to design and implement a user-friendly interface for users to discover and engage with various events.",
      "- Utilized modern web development technologies to ensure a responsive and intuitive user experience across different devices.",
      "- Developed an all-inclusive platform for events and volunteers with advanced features.",
      "- Integrated authentication and authorization mechanisms to ensure secure access to the platform and protect user privacy.",
    ],
    tools: ["Next js", "React js", "tailwind css", "Spring boot", "postgresql"],
    demo: "/projects/jolmer2.png",
    github_status: "Private Github",
    github:
      "https://github.com/incubation-center/B8-FullStack--Website--Group5",
    video_demo: "",
    publish: "https://www.jolmer.me/",
  },
  {
    id: 2,
    project: "Chatbot",
    img: "/Icons/chatbot.jpg",
    project_description: "Online Event Management Using Chatbot",
    project_date: "January 1, 2022 - April 1, 2022",
    job_level: "Junior Level",
    Type: "Internship",
    Company: "The internship from Japanese Company",
    position: "Backend Developer",
    project_id: "Online Event Management",
    work_exp: [
      "- Developed chatbots using Node.js backend and Dialogflow to meet client's needs and specifications",
      "- Managed and modified chatbots based on client feedback and requirements",
      "- Conducted thorough testing to ensure chatbots functioned effectively and met client expectations",
      "- Collaborated with front-end developer to integrate chatbot into website and messenger",
    ],
    tools: ["Node js", "Dialogflow", "Meta Developer"],
    demo: "/projects/chatbot.gif",
    github_status: "Private GitLab",
    github: "https://gitlab.com/Yeansovanvathana/meetnewpeople",
    video_demo: "",
    publish: "",
  },

  {
    id: 3,
    project: "Point of Sale System",
    img: "/Icons/pos.svg",
    project_description: "Shop Mangement System And Print Invoice",
    project_date: "November 11, 2022 - January 20, 2023",
    job_level: "Junior Level",
    Type: "Internship",
    Company: "The internship from Incubation Center(KIT)",
    position: "FullStack Developer",
    project_id: "Point of Sale (POS)",
    work_exp: [
      "- The project is to create a store management system developing a desktop application using Electron.js.",
      "- Designed the application's structure and backend using Nest.js and Developed the frontend using React.js",
      "- Overcame various challenges with the backend and worked closely with the team to identify and implement solutions to improve the system's performance.",
      "- Communicated regularly with the team to ensure that project goals and timelines were met.",
    ],
    tools: ["Nest js", "React js", "Electron js", "Postgresql"],
    demo: "/projects/pos.png",
    github_status: "Github",
    github: "https://github.com/Yeansovanvathana/Api_POS.git",
    video_demo: "https://youtu.be/irmHygchiCg",
    publish: "",
  },
  {
    id: 4,
    project: "Food Delivery App",
    img: "/Icons/vnham.png",
    project_description:
      "Vnham, a food delivery application, is located in the Kirirom Mountain",
    project_date: "January 24, 2022 - March 14, 2022",
    job_level: "Junior Level",
    Type: "Internship",
    Company: "The internship from Incubation Center(KIT)",
    position: "Project Leader",
    project_id: "Food Delivery (Vnham)",
    work_exp: [
      "- Developed the initial concept and idea for the VNHam food delivery project, considering market research and target audience",
      "- Identified and resolved project challenges promptly, making informed decisions to keep the project on track",
      "- Devised a comprehensive project plan, assigned tasks based on team members' skills, and ensured timely completion",
      "- Successfully launched VNHam food delivery Playstore, achieved satisfaction",
    ],
    tools: ["Flutter", "Dart", "Firebase"],
    demo: "/projects/vnhamPic2.png",
    github_status: "Github",
    github: "https://github.com/Yeansovanvathana/Food_Delivery_PVK.git",
    video_demo: "https://youtu.be/L9PfExZBrBo",
    publish:
      "https://play.google.com/store/apps/details?id=com.Vnham.newappname&pli=1",
  },
  {
    id: 5,
    project: "ZombiteMe",
    img: "/Icons/zombitemeIcon.png",
    project_description:
      "Zombiteme is the journey game that go through zombie places",
    project_date: "May 1, 2022 - August 1, 2022",
    job_level: "Junior Level",
    Type: "Internship",
    Company: "The internship from Incubation Center(KIT)",
    position: "Project Leader And Developer",
    project_id: "ZombiteMe (Action Game)",
    work_exp: [
      "- As the project lead and developer of Zombiteme, I was responsible for overseeing the entire project, from its initial concept to its final execution.",
      "- To create an immersive experience, I integrated numerous obstacles that challenge players and require skillful navigation to advance in the game.",
      "- Emphasizing the importance of high-quality animations, I ensured that every movement and action in Zombiteme was visually appealing, enhancing the overall gaming experience.",
      "- Successfully launched Zombiteme on Playstore, receiving positive feedback and satisfying players with its engaging gameplay.",
    ],
    tools: ["Unity", "C++", "Photoshop"],
    demo: "/projects/level3.gif",
    github_status: "Github",
    github: "https://github.com/Yeansovanvathana/zombiteme.git",
    video_demo: "https://youtu.be/lYrw9LJ23eQ",
    publish: "https://play.google.com/store/apps/details?id=com.KIT.zombiteMe",
  },
  {
    id: 6,
    project: "Rating System",
    img: "/Icons/KEEN.jpg",
    project_description:
      "Food rating system for collects data to help improve the quality of food in moringa(KIT)",
    project_date: "July 1, 2022 - September 30, 2022",
    job_level: "Junior Level",
    Type: "Internship",
    Company: "The internship from Virtual Company (KEEN)",
    position: "Developer",
    project_id: "Resort Sensor System",
    work_exp: [
      "- Collaborated with a team to develop a web platform that allowed students to provide feedback on their school's food issue.",
      "- Developed the front-end of the platform using Vue.js to create a user-friendly and visually appealing interface.",
      "- Worked closely with the team to ensure that the design was implemented accurately and effectively.",
    ],
    tools: ["Vue js", "Node js"],
    demo: "/projects/resort sensor system.png",
    github_status: "Private GitLab",
    github:
      "https://gitlab.com/KEEN-VC/RD/Resort-Rating-System/resort-sensor-system",
    video_demo: "",
    publish: "",
  },
  {
    id: 7,
    project: "OTP Verification",
    img: "/Icons/otp.png",
    project_description:
      "The project implemented a simple OTP system for user authentication",
    project_date: "February 17, 2022 - March 14, 2023",
    job_level: "Junior Level",
    Type: "Internship",
    Company: "Task from Japanese Company(Internship)",
    position: "Developer",
    project_id: "OPT Verification",
    work_exp: [
      "- The goal of the project was to create a reliable and secure OTP verification mechanism for user authentication.",
      "- I extensively researched and implemented the SMS Retriever API for feature provided by Android for retrieving verification codes sent via SMS",
    ],
    tools: ["Java", "Android Studio", "SMS API"],
    demo: "/projects/OTP.gif",
    github_status: "Github",
    github: "https://github.com/Yeansovanvathana/otp_verification.git",
    video_demo: "",
    publish: "",
  },
  // {
  //     id: 8,
  //     project: "Health Checking",
  //     img: "/Icons/health.jpg",
  //     project_description:
  //         "Tracking Personal health by review and checking note on each day",
  //     project_date: "April 1, 2022 - May 1, 2023",
  //     job_level: "Junior Level",
  //     Type: "Personal Project",
  //     Company: "Personal Project",
  //     position: "Developer",
  //     project_id: "Health Checking",
  //     work_exp: [
  //         "- I learn more Node js application with a front-end using Handlebars templating engine, implementing features such as secure password handling with bcrypt and authentication using Firebase. ",
  //         "- Additionally, I built a login page for seamless user experience, enhancing the overall usability and security of the application.",
  //     ],
  //     tools: ["Node js", "Handlebars", "Firebase"],
  //     demo: "/projects/main health.png",
  //     github_status: "Github",
  //     github: "https://github.com/Yeansovanvathana/Health_Project.git",
  //     video_demo: "",
  //     publish: "",
  // },
  // {
  //     id: 9,
  //     project: "Spotify Clone",
  //     img: "/Icons/Spotify_icon.svg.png",
  //     project_description:
  //         "Spotify clone 2.0 with the latest update UI of spotify 2023",
  //     project_date: "May 22, 2023 - May 25, 2023",
  //     job_level: "Junior Level",
  //     Type: "Personal Project",
  //     Company: "Personal Project",
  //     position: "Developer",
  //     project_id: "Spotify 2.0",
  //     work_exp: [
  //         "- I have learn new thing on spotify api and authentication also spotify-web-api-node.",
  //         "- Additionally, I have learn to use recoil as state management with react",
  //     ],
  //     tools: ["React js", "Next js"],
  //     demo: "/projects/spotiy.png",
  //     github_status: "Github",
  //     github: "https://github.com/Yeansovanvathana/Spotify_2.0.git",
  //     video_demo: "",
  //     publish: "",
  // },
];
