export const Exp = [
  {
    id: 1,
    project: "Chatbot",
    img: "/Icons/chatbot.jpg",
    project_description: "Online Event Management Using Chatbot",
    project_date: "January 1, 2022 - April 1, 2022",
    job_level: "Junior Level",
    Type: "Internship",
    Company: "The internship from Japanese Company",
    position: "Backend Developer",
    project_id: "Online Event Management Project",
    work_exp: [
      "- Developed chatbots using Node.js backend and Dialogflow to meet client's needs and specifications",
      "- Managed and modified chatbots based on client feedback and requirements",
      "- Conducted thorough testing to ensure chatbots functioned effectively and met client expectations",
      "- Collaborated with front-end developer to integrate chatbot into website and messenger",
    ],
    tools: ["Node js", "Dialogflow", "Meta Developer"],
    demo: "/projects/chatbot.gif",
    github_status: "Private Github",
    github: "",
  },

  {
    id: 2,
    project: "Point of Sale System",
    img: "/Icons/pos.svg",
    project_description: "Shop Mangement System And Print Invoice",
    project_date: "November 11, 2022 - January 20, 2023",
    job_level: "Junior Level",
    Type: "Internship",
    Company: "The internship from Incubation Center(KIT)",
    position: "FullStack Developer",
    project_id: "Point of Sale (POS)",
    work_exp: [
      "- The project is to create a store management system developing a desktop application using Electron.js.",
      "- Designed the application's structure and backend using Nest.js and Developed the frontend using React.js",
      "- Overcame various challenges with the backend and worked closely with the team to identify and implement solutions to improve the system's performance.",
      "- Communicated regularly with the team to ensure that project goals and timelines were met.",
    ],
    tools: ["Nest js", "React js", "Electron js", "Postgresql"],
    demo: "/projects/pos.png",
    github_status: "Github",
    github: "https://github.com/Yeansovanvathana/Api_POS.git",
    video_demo: "https://youtu.be/irmHygchiCg",
  },
  {
    id: 3,
    project: "Chatbot",
    img: "/Icons/adobe-xd-1-logo-svgrepo-com.svg",
    project_description: "Online Event Management Using Chatbot",
    project_date: "January 1, 2022 - April 1, 2022",
    job_level: "Junior Level",
    Type: "Internship",
    Company: "The internship from Incubation Center(KIT)",
    position: "FullStack Developer",
    project_id: "Point of Sale (POS)",
    work_exp: [
      "- The project is to create a Point of Sale (POS) system by developing a desktop application using Electron.js.",
      "- Designed the application's structure and backend using Nest.js and Developed the frontend using React.js",
      "- Overcame various challenges with the backend and worked closely with the team to identify and implement solutions to improve the system's performance.",
      "- Communicated regularly with the team to ensure that project goals and timelines were met.",
    ],
    tools: [
      "Nest js",
      "React js",
      "Electron js",
      "Postgresql",
      "Postgresql",
      "Postgresql",
      "Postgresql",
    ],
    demo: "/projects/chatbot.gif",
    github_status: "Private Github",
    github: "",
  },
];
